### PR TITLE
No way to quit 2

### LINKED ISSUE #2: No way to quit
There's no way for a user to exit the game once entered.  He/she must either die or complete the game before being allowed to quit back to the BBS.  This often results in users simply hanging-up on the BBS after starting.

A simple menu at the beginning like 1-Play, 2-Instructions, 3-Quit, or even a courtesy prompt  asking, "are you ready?" would make it both caller and BBS friendly.

### PR DESCRIPTION
**Pull request by chairmanmow**

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
It's an improvement, and does give the user a chance to back out before playing

However when choosing "2" for instructions, after displaying them, it drops the player straight into the game, bypassing the `rifleskills` function in the process.

I tried adding a while loop onto your changes, and made the `firstprompt` function return the `yesNo` value.  It should keep the user out of the game unless they explicitly select "1".

```javascript
	var userSelection = "0";
	while (userSelection != "1") {
		userSelection = firstPrompt();
	}	
	rifleSkills();  // finds out what your shooting level is 
	initialPurchase();
	firstTurn();

	//log(eventNo.toSource());
	function firstPrompt() {
		console.putmsg("\r\n\r\n1 - Play \r\n2 - Instructions\r\n3 - Quit\r\n");
		yesNo = console.getstr();
		yesNo = yesNo.toUpperCase();
		//if (yesNo == "1") {
		//	rifleSkills();
		// return;
		//}
		if (yesNo == "2") {
			instructions();
			// return 
		}
		if (yesNo == "3") {
			throw "gameOver";
			// return 
		}

		//firstPrompt();
		return yesNo;
	}
```
I think the combination of your menu and the loop does the trick.  Thoughts?

**Comment by chairmanmow** [comment]
@CraigEMP If it works, that works for me, this door is coded in a pretty haphazard style, but it's gratifying to know it lives!  Off topic, but fyi, I also made another door game a couple years later for synchronet that's much neater in my opinion, but isn't really as well known as I stopped bbs'ing as much, looks like you might not have it on your board, maybe worth checking out : https://github.com/chairmanmow/stacktion

**Comment by chairmanmow** [comment]
@CraigEMP So I committed that change btw, let me know if that's what you were thinking and if it's working with my update, and then can merge it.

**Review by ghost — COMMENTED** [review]
That worked nicely!  Thanks.

**Review by ghost — APPROVED** [review]

**Comment by chairmanmow** [comment]
@CraigEMP Thanks for checking it out, glad we could get it sorted! Cheers!

**Comment by ghost** [comment]
> Off topic, but fyi, I also made another door game a couple years later for synchronet that's much neater in my opinion, but isn't really as well known as I stopped bbs'ing as much, looks like you might not have it on your board, maybe worth checking out : https://github.com/chairmanmow/stacktion

I installed this and tried it out.  Interesting concept for a game.  Thanks for making it and recommending it.  If you ever feel like BBS'ing again, drop by mine: [conchaos.synchro.net](https://conchaos.synchro.net)

Thanks again.

**Comment by andy5995** [comment]
>ever feel like BBS'ing again, drop by mine: [conchaos.synchro.net](https://conchaos.synchro.net)
> 

Hi @CraigEMP , if you're actively advertising your BBS, feel free to add it to the short list in the README here https://github.com/theimpossibleastronaut/modemu2k/blob/master/README

**Pull request merged**
